logs: 
    - name: root
      level: debug
      formatter: '%d%T%m%n'
      appender: 
        - type: StdoutLogAppender
          formatter: '%d %t%T%m%n'
    - name: system
      level: debug
      appender: 
        - type: FileLogAppender
          level: debug
          file: /home/lee/projects/VScode/myProject/log/sys_log.txt
          formatter: '[%p]%T%d{%Y-%m-%d %H:%M:%S} %t %F <%f:%l>%T%m %n'
        - type: StdoutLogAppender
          formatter: '[%p]%T%d{%Y-%m-%d %H:%M:%S} %t %F <%f:%l>%T%m %n'
    - name: test
      level: debug
      appender: 
        - type: FileLogAppender
          level: debug
          file: /home/lee/projects/VScode/myProject/log/test_log.txt
          formatter: '%d{%Y-%m-%d %H:%M:%S}%T%p%T%m%n'
    - name: mutex
      level: debug
      appender: 
        - type: FileLogAppender
          level: debug
          file: /home/lee/projects/VScode/myProject/log/mutex.txt
          formatter: '%p%m%n'
system:
    port: 999
    value: 000
